services:
  db:
    image: postgres:16-alpine
    container_name: django_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lemana_pro_online
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: fma160392
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d lemana_pro_online"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: "0"
      SECRET_KEY: "gPm9rKjWtZfBvDqLxHsN3cR5yU7wA1eT4iM6o8pQ0sF2hJnCvXzYbGdEaBcDfG"
      DB_NAME: "lemana_pro_online"
      DB_USER: "admin_user"
      DB_PASSWORD: "fma160392"
      DB_HOST: "db"
      DB_PORT: "5432"
      HOST_NAME: "lemana-pro.online"
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             exec gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi:application"

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"  # Добавляем HTTPS порт
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Для SSL сертификатов
      - static_volume:/static:ro
      - media_volume:/media:ro
      - certbot_data:/etc/letsencrypt  # Volume для Certbot
      - certbot_challenge:/var/www/certbot  # Для HTTP challenge

  certbot:
    image: certbot/certbot
    container_name: django_certbot
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_challenge:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d lemana-pro.online -d www.lemana-pro.online --agree-tos

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_data:
  certbot_challenge: