services:
  db:
    image: postgres:16-alpine
    container_name: django_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lemana_pro_online
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: fma160392
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d lemana_pro_online"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: "0"
      SECRET_KEY: "gPm9rKjWtZfBvDqLxHsN3cR5yU7wA1eT4iM6o8pQ0sF2hJnCvXzYbGdEaBcDfG"
      DB_NAME: "lemana_pro_online"
      DB_USER: "admin_user"
      DB_PASSWORD: "fma160392"
      DB_HOST: "db"
      DB_PORT: "5432"
      HOST_NAME: "lemana-pro.online"
      # Добавляем переменные для HTTPS
      SECURE_SSL_REDIRECT: "True"
      SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             exec gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi:application"

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      # Открываем порты 80 и 443
      - "80:80"
      - "443:443"
    volumes:
      # Используем SSL конфиг
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
      # Монтируем сертификаты Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  static_volume:
  media_volume: